#!/usr/bin/env python3
"""Re-derive the deployment identity from the tree, after integration.

SUPERSEDED BY THE V5 SECTION 14 SPLIT -- READ THIS BEFORE USING IT.

This tool recomputes `compatibility.lock.json -> deployment.identity` from
`deployment.inputs`, and it is the tool that made the defect visible: it reports
which file-derived inputs moved. What it CANNOT do is stop them moving, because
the identity it recomputes is a hash over files in the SAME tree that records it.
Five of those inputs are digests of files in this repository:

    host_profile_digest                  -> profiles/daily-candidate/cordis.patch.yml
    agent_preset_digest                  -> profiles/.../daily-standard/agent.cordis.yml
    resolved_plugin_graph_digest         -> qualification/results/M3.1-c2-profile/dump-*.yml
    acceptance_spec_sha256               -> qualification/specs/acceptance-spec.json
    trusted_local_acceptance_spec_sha256 -> qualification/specs/frozen/*.as-authored.json

So editing any of them moves the identity, adopting the move is another edit, and
the identity moved FOUR TIMES in one wave. The last move was S1's
`includeShippedRoot: false` -- a change the round-2 brief explicitly authorizes,
which invalidated the identity anyway because the identity is computed over the
file the change edited. A CORRECT change moving the identity is the defect.

WHAT REPLACED IT (V5 section 14):

    compatibility.expected.json   checked in, REQUIREMENTS. No digest of any file
                                  in this repository, so no edit to the deployment
                                  can move it. Checked by
                                  `python qualification/runners/build-manifest.py --check-expected`.
    BuildManifest                 GENERATED, a qualification/release artifact.
                                  RuntimeDeploymentIdentity = H(canonical manifest).
                                  QualificationContractIdentity adds the definition
                                  and runner digests. Results bind to the contract
                                  identity. Generated by
                                  `node qualification/runners/run-p14-manifest.mjs`
                                  then `python qualification/runners/build-manifest.py
                                  --from-observation ...`.

SO WHY DOES THIS FILE STILL EXIST, AND STILL RUN?

Because the old identity is still RECORDED in the lock and still cited by 84 PASS
rows in `qualification/gates.json`, and a reader must be able to check whether it
still describes this tree. Deleting the tool would leave those citations
unfalsifiable. What this file is FOR now is exactly that: a statement about a
SUPERSEDED identity, kept honest rather than kept authoritative.

WHAT IT STILL DOES NOT DO, and the reason it refuses to write: a digest proves the
inputs have not changed since it was computed, not that they are right. Two of this
project's six re-derivations were corrections of real defects (a Windows path
mangled by Python escape processing; a missing drive-letter strip on the preset
root). Each time the identity was internally consistent and wrong.

USAGE
    python helpers/rederive-identity.py            # report only
    python helpers/rederive-identity.py --json     # machine-readable
"""
from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
LOCK = ROOT / "compatibility.lock.json"
EXPECTED = ROOT / "compatibility.expected.json"

# Inputs whose value is a digest OF A FILE. Keyed by input name -> repo path.
# A new file-derived input is added here in one place; doctor.py carries the same
# map for its check, and the two are deliberately separate so a mistake in one
# does not silently agree with itself.
#
# THESE ARE THE FIVE THAT MADE THE IDENTITY SELF-REFERENTIAL. The map is kept
# because it is what SHOWS the self-reference: every row below is a digest of a
# file inside the same commit that records the digest.
FILE_INPUTS = {
    "host_profile_digest": "profiles/daily-candidate/cordis.patch.yml",
    "agent_preset_digest": "profiles/daily-candidate/presets/daily-standard/agent.cordis.yml",
    "acceptance_spec_sha256": "qualification/specs/acceptance-spec.json",
    "trusted_local_acceptance_spec_sha256":
        "qualification/specs/frozen/acceptance-spec.trusted-local-v1.as-authored.json",
}

# The one input that is NOT in FILE_INPUTS and SHOULD HAVE BEEN, recorded as a
# separate fact because its absence was the hole `identity-input-unchecked-and-stale.md`
# documented: no tool checked it, and its basis was a pre-F3 dump whose
# `sandbox-policy.mode` still read the confining `workspace-write`.
#
# It is checked here now. The value it should be is NOT recomputed into the
# identity, because the fresh runtime graph lives in the generated BuildManifest --
# a dump is what the loader DECLARED and this file cannot produce what it
# ACTIVATED. So the check reports whether the recorded value still matches the
# file it names, and says plainly that matching does not make it current.
UNCHECKED_GRAPH_INPUT = {
    "input": "resolved_plugin_graph_digest",
    "basis": "qualification/results/M3.1-c2-profile/dump-config-daily-candidate.yml",
    "superseded_by": "the generated BuildManifest's resolved_plugin_graph, freshly observed with realpaths",
}

# The artifact digest is over the BUILT launcher, not a repo file, so it is
# checked separately against the path the lock itself names.
ARTIFACT_INPUT = "artifact_sha256"
LAUNCHER_INPUT = "launcher_realpath"


def sha256_file(path: pathlib.Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def identity_digest(inputs: dict) -> str:
    """The identity's declared algorithm, quoted from the lock:
    sha256(UTF8(json.dumps(inputs, sort_keys=True, separators=(',', ':'), ensure_ascii=True)))
    """
    payload = json.dumps(inputs, sort_keys=True, separators=(",", ":"), ensure_ascii=True)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def main() -> int:
    ap = argparse.ArgumentParser(description="re-derive the SUPERSEDED deployment identity (read-only)")
    ap.add_argument("--json", action="store_true", help="machine-readable output")
    args = ap.parse_args()

    lock = json.loads(LOCK.read_text(encoding="utf-8"))
    deployment = lock.get("deployment", {})
    recorded_inputs = deployment.get("inputs", {})
    recorded_identity = deployment.get("identity")

    if not recorded_inputs:
        print("the lock carries no deployment.inputs; nothing to re-derive", file=sys.stderr)
        return 2

    # Copy, so the recomputation is over exactly the declared input set.
    recomputed = dict(recorded_inputs)
    moves: list[dict] = []

    for name, rel in FILE_INPUTS.items():
        if name not in recomputed:
            continue
        path = ROOT / rel
        if not path.exists():
            moves.append({"input": name, "path": rel, "kind": "MISSING",
                          "recorded": recomputed[name], "computed": None})
            continue
        actual = sha256_file(path)
        if actual != recomputed[name]:
            moves.append({"input": name, "path": rel, "kind": "CHANGED",
                          "recorded": recomputed[name], "computed": actual})
        recomputed[name] = actual

    # The launcher: the lock names a path, and its digest must agree.
    launcher_rel = recorded_inputs.get(LAUNCHER_INPUT)
    if launcher_rel:
        launcher = pathlib.Path(launcher_rel)
        if launcher.exists():
            actual = sha256_file(launcher)
            if actual != recomputed.get(ARTIFACT_INPUT):
                moves.append({"input": ARTIFACT_INPUT, "path": str(launcher),
                              "kind": "CHANGED", "recorded": recomputed.get(ARTIFACT_INPUT),
                              "computed": actual})
            recomputed[ARTIFACT_INPUT] = actual
        else:
            moves.append({"input": ARTIFACT_INPUT, "path": str(launcher), "kind": "MISSING",
                          "recorded": recomputed.get(ARTIFACT_INPUT), "computed": None})

    # ── the input that NO tool checked, now checked ─────────────────────────
    #
    # THE HOLE THIS CLOSES, from qualification/results/ROOT-round2/
    # identity-input-unchecked-and-stale.md, re-measured for this change:
    #
    #     $ grep -c resolved_plugin_graph_digest helpers/rederive-identity.py helpers/doctor.py
    #     helpers/rederive-identity.py:0
    #     helpers/doctor.py:0
    #
    # So a stale value here was invisible to both gates. This check reports whether
    # the recorded value matches the file it names, and SEPARATELY reports the fact
    # that matching is not the same as current -- because the basis dump predates F3
    # and still contains the confining mode CMP-02 exists to catch.
    graph_check: dict | None = None
    recorded_graph = recorded_inputs.get(UNCHECKED_GRAPH_INPUT["input"])
    basis = ROOT / UNCHECKED_GRAPH_INPUT["basis"]
    if recorded_graph is not None:
        graph_check = {
            "input": UNCHECKED_GRAPH_INPUT["input"],
            "recorded": recorded_graph,
            "basis": UNCHECKED_GRAPH_INPUT["basis"],
            "basis_exists": basis.is_file(),
            "basis_sha256": sha256_file(basis) if basis.is_file() else None,
            "matches_basis": (sha256_file(basis) == recorded_graph) if basis.is_file() else None,
            "superseded_by": UNCHECKED_GRAPH_INPUT["superseded_by"],
        }
        if graph_check["matches_basis"] is False:
            moves.append({"input": UNCHECKED_GRAPH_INPUT["input"], "path": UNCHECKED_GRAPH_INPUT["basis"],
                          "kind": "CHANGED", "recorded": recorded_graph,
                          "computed": graph_check["basis_sha256"]})
        # NOT folded into `recomputed`: the fresh graph is a RUNTIME observation and
        # cannot be recomputed from a file. Substituting the dump's own digest would
        # make the identity certify a dump again, which is the defect being removed.
        graph_check["why_not_recomputed_into_the_identity"] = (
            "a dump is what the loader DECLARED; the resolved graph is what it "
            "ACTIVATED, and only a live boot can observe it. Substituting the dump's "
            "digest would make this identity certify the declared graph again -- the "
            "defect being removed. The fresh value is in the generated BuildManifest.")

    new_identity = identity_digest(recomputed)

    if args.json:
        print(json.dumps({
            "superseded": True,
            "superseded_by": "compatibility.expected.json + the generated BuildManifest (V5 section 14)",
            "recorded_identity": recorded_identity,
            "recomputed_identity": new_identity,
            "identity_moved": new_identity != recorded_identity,
            "input_moves": moves,
            "unchecked_graph_input": graph_check,
        }, indent=1))
        return 0

    print("THIS IDENTITY IS SUPERSEDED. V5 section 14 split it into:")
    print("  compatibility.expected.json   (requirements; no digest of any file in this repo)")
    print("  BuildManifest                 (generated; RuntimeDeploymentIdentity = H(canonical manifest))")
    print("  Result/evidence files bind to QualificationContractIdentity.")
    print("  Check the requirements:  python qualification/runners/build-manifest.py --check-expected")
    print("  Generate the manifest:   node qualification/runners/run-p14-manifest.mjs")
    print("                           python qualification/runners/build-manifest.py --from-observation ...")
    print("")
    print("What follows describes the SUPERSEDED identity, and is kept because the lock")
    print("still records it and 84 PASS rows in qualification/gates.json still cite it.")
    print("")
    print(f"recorded identity  : {recorded_identity}")
    print(f"recomputed identity: {new_identity}")
    print()
    if not moves:
        print("no file-derived input moved. The superseded identity still describes this tree.")
    else:
        print(f"{len(moves)} input(s) moved:")
        for m in moves:
            print(f"  {m['input']}")
            print(f"    {m['kind']}: {m['path']}")
            print(f"    recorded: {str(m['recorded'])[:32]}")
            print(f"    computed: {str(m['computed'])[:32]}")
        print()
        print("EVERY VERDICT BOUND TO THE OLD IDENTITY IS NOW STALE. That is intended:")
        print("an identity proves the inputs have not changed, not that they are right.")
        print()
        print("BUT A MOVE IS NOT AUTOMATICALLY A CORRECTION. Two of this project's six")
        print("re-derivations were fixes for real defects (a Windows path mangled by")
        print("Python escape processing; a missing drive-letter strip on the preset root).")
        print("Decide for EACH move whether it is an intended change or a defect, and")
        print("record which. This tool does not write the lock.")
    print()
    if graph_check is not None:
        print(f"the input NO tool used to check -- {graph_check['input']}:")
        print(f"  basis            {graph_check['basis']}")
        print(f"  matches its file {graph_check['matches_basis']}")
        print("  BUT MATCHING IS NOT CURRENT. That dump predates F3 and its sandbox-policy")
        print("  row still reads `mode: workspace-write` -- the CONFINING mode CMP-02 exists")
        print("  to catch -- while this tree resolves `danger-full-access`. An identity input")
        print("  that matches its file is a faithful digest of a stale graph.")
        print(f"  Superseded by: {graph_check['superseded_by']}")
        print()
    print("To adopt the superseded identity, edit deployment.inputs and deployment.identity in")
    print("compatibility.lock.json deliberately, then run helpers/doctor.py. That is NOT the")
    print("recommended action any more: the recommended action is to bind results to the")
    print("generated manifest's QualificationContractIdentity instead.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
